const projectData = [
  {
    id: 1,
    image: '/images/sample-design-1.jpg',
    title: 'Bungalow Type',
    description:
      'Single Storey Residence Project Located at Balibago, Angles City Pampanga.',
    listTitle: 'Design and Build',
    bedrooms: 3,
    cr: 2,
    sq: 200,
    area: ['Living area', 'Dining area', 'Kitchen', 'Basketball Court'],
    price: '3,200,000.00',
  },
  {
    id: 2,
    image: '/images/sample-design-2.jpg',
    title: 'Single Family Type',
    description: 'Two Storey Residence Project.',
    listTitle: 'Design and Build',
    bedrooms: 4,
    cr: 2,
    sq: 150,
    area: ['Living area', 'Dining area', 'Kitchen', 'Garage'],
    price: '3,400,000.00',
  },
  {
    id: 3,
    image: '/images/sample-design-3.jpg',
    title: 'Delux Type',
    description: 'Two Storey Residence Project.',
    listTitle: 'Design and Build',
    bedrooms: 5,
    cr: 3,
    sq: 130,
    area: ['Living area', 'Dining area', 'Kitchen', 'Balcony ', 'Garage'],
    price: '4,000,000.00',
  },
  {
    id: 4,
    image: '/images/sample-design-4.jpg',
    title: 'Supreme Residence Type',
    description: 'Two Storey Residence Project.',
    listTitle: 'Design and Build',
    bedrooms: 5,
    cr: 3,
    sq: 200,
    area: ['Living area', 'Dining area', 'Kitchen', 'Garage'],
    price: '4,000,000.00',
  },
];
export default projectData;
